name 'irfu-omd'
version '0.1.0'

author 'F.Schaer'
license 'Cecil v3'
summary 'Allows to install configure and tune an OMD distribution and OMD sites'
dependency 'puppetlabs/stdlib', ''
dependency 'puppetlabs/concat', ''
dependency 'puppetlabs/xinetd', ''
dependency 'puppetlabs/apt', ''
